---
- name: Run remote Docker installer script from GitHub
  hosts: all
  become: true

  vars:
    script_url: "https://raw.githubusercontent.com/nfworking/temp/main/installdocker.sh"
    local_path: "/tmp/installdocker.sh"

  tasks:
    - name: Download the install script from GitHub
      ansible.builtin.get_url:
        url: "{{ script_url }}"
        dest: "{{ local_path }}"
        mode: '0755'

    - name: Run the Docker install script
      ansible.builtin.shell: "{{ local_path }}"
