---
- name: Setup Docker environment on Ubuntu
  hosts: all
  become: true

  vars:
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_keyring_path: /etc/apt/keyrings/docker.gpg
    docker_repo_path: /etc/apt/sources.list.d/docker.list
    docker_repo_entry: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

  tasks:
    - name: Ensure apt keyring directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key to keyring
      get_url:
        url: "{{ docker_gpg_url }}"
        dest: "{{ docker_keyring_path }}"
        mode: '0644'

    - name: Add Docker repository manually
      copy:
        dest: "{{ docker_repo_path }}"
        content: "{{ docker_repo_entry }}\n"
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker and useful tools
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - nano
          - git
          - btop
        state: present

    - name: Add svradmin user to docker group
      user:
        name: svradmin
        groups: docker
        append: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started
