---
# Playbook to install Docker and essential tools on Ubuntu systems.
# It handles adding the Docker GPG key, setting up the repository,
# installing Docker components, and adding a user to the Docker group.

- name: Install Docker and tools on Ubuntu
  hosts: all
  become: true

  vars:
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_keyring_path: /etc/apt/keyrings/docker.gpg
    docker_repo_path: /etc/apt/sources.list.d/docker.list
    docker_repo_entry: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable"

  tasks:
    - name: Ensure apt keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: "{{ docker_gpg_url }}"
        dest: "{{ docker_keyring_path }}"
        mode: '0644'

    - name: Add Docker APT repository
      ansible.builtin.copy:
        dest: "{{ docker_repo_path }}"
        content: "{{ docker_repo_entry }}\n"
        mode: '0644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker, Compose plugin, and tools
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - nano
          - git
          - btop
        state: present

    - name: Add svradmin to docker group
      ansible.builtin.user:
        name: svradmin
        groups: docker
        append: yes

    - name: Enable and start Docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
