---
- name: Install Docker and tools on Ubuntu
  hosts: all
  become: true

  vars:
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_keyring_path: /etc/apt/keyrings/docker.gpg
    docker_repo_path: /etc/apt/sources.list.d/docker.list
    docker_repo_entry: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable"

  tasks:
    - name: Ensure apt keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: "{{ docker_gpg_url }}"
        dest: "{{ docker_keyring_path }}"
        mode: '0644'

    - name: Write Docker APT repository manually
       shell: |
         echo "{{ docker_repo_entry }}" > /etc/apt/sources.list.d/docker.list
         args:
         executable: /bin/bash
 

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker, Compose plugin, and tools
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - nano
          - git
          - btop
        state: present

    - name: Add svradmin to docker group
      user:
        name: svradmin
        groups: docker
        append: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started
